### ISSUE TITLE
Calling nana::textbox::tooltip("") after calling tooltip() with a nontrivial string causes an error

### ISSUE THREAD

**Issue by jk-jeon** [cnjinhao/nana#331] opened 2018-08-23 20:16 UTC
(Nana 1.6.1)

It causes access violations.

If the tooltip is in display when `tooltip("")` is called, I got an error thrown in the file `tooltip.cpp`, line 236.
(`window_.reset()`)
It seems that `window_` is not properly initialized.

If the tooltip is not in display when `tooltip("")` is called, an error is thrown if I reopen the tooltip by hovering the mouse on the textbox. The error is thrown in the file `tooltip.cpp`, line 291.
(`cont_.emplace_back(wd, std::string())`)

Thanks.

**Comment by cnjinhao** [comment] 2018-08-24 22:09
Thank you for reporting this issue. A fix has been checked into hotfix branch.

**Comment by jk-jeon** [comment] 2018-08-25 06:57
Thank you. So the issue has been fixed? (because you didn't close this issue)
Seems working now.

**Comment by cnjinhao** [comment] 2018-08-26 09:05
Fixed. Once you confirm this fix, you can close the issue. If the issue is still opened and no any feedback, I will close it when a new version is released.

**Closed** 2018-08-30 17:34 UTC
